# Generated by Django 5.1.4 on 2024-12-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
