# Generated by Django 5.0.10 on 2024-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0004_rename_ram_laptop_internal_storage_gb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='year',
        ),
        migrations.AddField(
            model_name='laptop',
            name='audio_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery_capacity_wh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='bluetooth_version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='depth_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_inch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_ratio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='gpu_extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='gpu_integrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='has_bluetooth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='has_touchscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='has_webcam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='height_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='keyboard_backlit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='keyboard_numpad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price_eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='psu_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='speakers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='wifi_standard',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery_life_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='internal_storage_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
