# Generated by Django 5.0.10 on 2024-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0005_remove_laptop_brand_remove_laptop_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
