# Generated by Django 5.0.10 on 2024-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0006_alter_laptop_bluetooth_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
